### ISSUE TITLE
Alternativ web-safe shrift qo'shilishi va sans-serif qo'shtirnoqsiz yozilishi kerak

### ISSUE THREAD

**Issue by Muhammadjewel** [Mr-Perfectuz/ansormed#1]
![image](https://user-images.githubusercontent.com/10514327/133124464-18f548db-d70e-4899-8f1a-fbc7a62347aa.png)

**Comment by Mr-Perfectuz** [comment]
alternative shrift qo'shildi va sans-serif shrifti qo'shtirnoqsiz yozildi
