### ISSUE TITLE
Sayt logotipi rasmi joylashuvi noto'g'ri ko'rsatilgan. Shu sabab rasm sahifada chiqmayapti. Rasm o'rniga undagi alternativ text chiqib turibdi

### ISSUE THREAD

**Issue by Javohirshakh** [Mr-Perfectuz/ansormed#2]
![image](https://user-images.githubusercontent.com/77332200/133437054-7f3f8683-6a93-46bf-b5f0-f63deb39988b.png)

**Comment by Javohirshakh** [comment]
footerda ham huddi shu narsa takrorlangan

**Comment by Mr-Perfectuz** [comment]
header and footer pictures has been adjusted
