### ISSUE TITLE
Kontent rasmlar figmadan noto'g'ri olingan. 

### ISSUE THREAD

**Issue by Javohirshakh** [Mr-Perfectuz/ansormed#3]
Ya'ni faqatgina rasmning o'zi emas, uning atrofida oq qismlar ham qo'shilib olingan. Bu narsa Xizmatlar bo'limidagi 4 ta rasmda takrorlangan.
Bu rasmni brauzerda ochilgan holati:
![image](https://user-images.githubusercontent.com/77332200/133437934-4c7259c9-817b-4def-86ed-0ec1bd958df5.png)

**Comment by Mr-Perfectuz** [comment]
done
