### ISSUE TITLE
Sahifada container ishlatilmagan

### ISSUE THREAD

**Issue by Javohirshakh** [Mr-Perfectuz/ansormed#4]
Sahifada container ishlatilmagan.
kattaroq displayda ochilsa sahifa ko'rinishi buzilib ketadi. Shunday bo'lmasligi uchun ham container ishlatilishi kerak
![image](https://user-images.githubusercontent.com/77332200/133440258-3069042e-c846-422f-a5bb-12cafb4ba25c.png)

**Comment by Mr-Perfectuz** [comment]
header sahifa container ichiga olindi
