### ISSUE TITLE
Ro'yhatdan o'tish qismida elementlar o'rtada joylashmagan

### ISSUE THREAD

**Issue by Javohirshakh** [Mr-Perfectuz/ansormed#6]
Ikkala elementga ham o'ng tomondan joy tashlab ketilganligi sababli elementlar sal chaproqqa surulib qolgan
![image](https://user-images.githubusercontent.com/77332200/133441073-97e9323b-70d9-42a2-bace-05a65a4f59f2.png)

**Comment by Mr-Perfectuz** [comment]
elementlar center ga olindi va birinchi buttonga margin-left berildi
